blueprint:
  test-data:
    enabled: true
  security:
    simple:
      enabled: true
      users:
        user:
          username: user
          password: user
          roles:
          - USER
          groups:
          - users
        admin:
          username: admin
          password: admin
          roles:
          - USER
          - ADMIN
          groups:
          - users
          - administrators

spring:
  main:
    banner-mode: "off"

logging:
  level:
    # Hide useless Micrometer warnings
    reactor.netty.tcp: ERROR

