blueprint:
  security:
    simple:
      enabled: true
      users:
        user:
          username: user
          password: user
          roles: USER
        admin:
          username: admin
          password: admin
          roles: ADMIN

spring:
  main:
    banner-mode: "off"
