sudo: required

language: java

# Don't run mvn install automatically
install: true

services:
  - docker

cache:
  yarn: true
  directories:
    - $HOME/.m2
    - blueprint-ui/src/main/frontend/node
    - blueprint-ui/src/main/frontend/node_modules

jdk:
  - openjdk8

before_script:
  # Disable services enabled by default
  - sudo service postgresql stop
  # Bring up docker images
  - docker-compose -f docker/docker-compose.yml up --build -d

script:
  - mvn install -Pintegration-test

after_script:
  - docker-compose -f docker/docker-compose.yml down