sudo: required

language: java

services:
  - docker

cache:
  yarn: true
  directories:
    - $HOME/.m2
    - blueprint-ui/src/main/frontend/node
    - blueprint-ui/src/main/frontend/node_modules

jdk:
  - openjdk8

before_script:
  - docker-compose up --build -d

script:
  - mvn install

after_script:
  - docker-compose down