version: "2"
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "sa"