katalog:
  clustering:
    #    hazelcast:
    #      instanceName: member-1
    #      port: 5701
    #      members:
    #        - localhost:5701
    #        - localhost:5702
    type: standalone
  security:
    auth:
      type: form
    users:
      user:
        username: user
        password: user
        email: user@foo.com
        roles:
          - USER
        groups:
          id-group1:
            - CREATE
            - READ
            - UPDATE
            - DELETE
          id-group2:
            - CREATE
            - READ
            - UPDATE
            - DELETE
          id-group3:
            - READ
      user2:
        username: user2
        password: user2
        email: user2@foo.com
        roles:
          - USER
        groups:
          id-group1:
            - READ
          id-group2:
            - CREATE
            - READ
            - UPDATE
            - DELETE
          id-group3:
            - CREATE
            - READ
            - UPDATE
            - DELETE
      admin:
        username: admin
        password: admin
        email: admin@foo.com
        roles:
          - USER
          - ADMIN
    groups:
      id-group1: group1
      id-group2: group2
      id-group3: group3
    token:
      # This is a base64 encoded HS512 'shared secret' signing key generated at https://mkjwk.org/
      hmacShaKey: ewogICJrdHkiOiAib2N0IiwKICAidXNlIjogInNpZyIsCiAgImsiOiAibks4TDNGVlA3WWtIdnRMRUUyMkl2LUVxYUM0d1VTRnRqWmZ5alFEWnpoUks5cnIxUFdJOFFVNXp0bGduNWVMQW9kZmdpS3plS3RCWFAyYlhYcFY3MVlCeDR0djVhcDc1V0pCVkpLWHFObEFzR1FWX3JncEVLeDdLekRKdlJwUzBwUldkbDNYZ25vbHlaX3g5UXJCb0dVVmxfcDZGSTdhWUJLRVZwc2g5Y3JRQWctUm5ZQWo0U0V4YlRuQ1gxY0RpWlZtZTlaSUQ4bDRKYWZwcmw5dWV4dnpHZVVzSDdodDVEcXVtZDFNOVlqUEw1SE1DaE1LdXpkbVpyRUx0UjFCOTdVZk0xTG5kUWdsSnViRC1IVTlpSmFneTNQUzZlRG52Nl9QZExtQVJoRWR3cHhjd1VHdEUxT0VIOF9PSGFieDEzUEt5bEVJZU9oM3AwOHRIOFhoQjhRIiwKICAiYWxnIjogIkhTNTEyIgp9

spring:
  main:
    banner-mode: "off"

logging:
  level:
    # Hide useless Micrometer warnings
    reactor.netty.tcp: ERROR
    #com.bol.katalog: DEBUG

